microsoft/ccf-app-samples

- banking-app/README.md
Closes #17 
Added a sentence to highlight that test.sh runs in its own sandbox.
> Added guidelines for running tests

- README.md
Basically followed https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-codespaces-badge
> Add back 'Open in GitHub Codespaces' button

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/user_story.md
This PR will add 3 issue types into GitHub so we can create bugs, stories and features. This will help close #49
> Add separate issue types to GitHub

- data-reconciliation-app/docs/data-schema-data-flow.md
Updates on data requirements and data flow following conversation with Brent
@julioalex-rezende please let me know if I am missing anything or anything else you feel is helpful to add to this doc.
Thanks!
> Data schema requirements and flow

- data-reconciliation-app/docs/data-reconciliation.md
Add a code sample to demonstrate how to generate a voting-based data reconciliation report
> Capture pseudo code from Forum App so we can document the Data Reconciliation

- banking-app/scripts/demo_governance.sh
It fixes broken `make demo` command in banking-app.
- [Run the demo in CI](https://github.com/microsoft/ccf-app-samples/issues/91)
> Fix path to scurl

- .github/workflows/ci.yml
Including `make test-docker-virtual` CI target for data-reconciliation-app
> adding docker flow for data-reconciliation ci

- data-reconciliation-app/docs/adr/02-data-schema-strategy.md
This ADR documents our decision on data schema definition strategy for data submission.
Fixes #101
> [ADR] - Data Schema Definition Strategy

- data-reconciliation-app/docs/adr/04-Authentication.md
Document how the users of Reconciliation apis will be authenticated #102
> Reconciliation APIs authentication mechanism ADR

- .github/workflows/cd.yml
Fixes #121 - changed the order of the deployment/test because different samples have a different constitution.
> Change test order to get main build working

- README.md
- deploy/README.md
This PR contains a couple of suggestions and fixes to the docs.
- It adds a link, in the main README.md, to explain what CCF is. I've picked what appears to be a good link, but perhaps there's a better one (happy to change it). This addresses #125 
- While I was here, I spotted a couple of instances of `it's` that should be `its`
Hope this is useful.
> Some Doc Updates

- data-reconciliation-app/docs/adr/02-data-schema-strategy.md
> data-schema-strategy review

- data-reconciliation-app/docs/adr/06-data-mutability.md
Light changes on writing for Data mutability ADR.
> Doc Review: 7 - Data mutability

- README.md
- auditable-logging-app/README.md
Have better links from the main readme to drive users to the samples
Fixes #5
> Signpost each sample from the main readme

- data-reconciliation-app/docs/adr/05-Reporting.md
- data-reconciliation-app/docs/adr/07-ingestion-format.md
Fix #168 
ADR Review: 
Reporting
> adr reporting review

- .tours/deploy-code-change-on-mccf.tour
- data-reconciliation-app/docs/managed-ccf-demo-guidance.md
The line number of the piece of code that you need to change for the "code change demo" has changed because we have now commented the TypeScript code!! 🤣
> Line numbers changed because of commented methods!

- data-reconciliation-app/src/endpoints/reporting.ts
- deploy/README.md
Typo in the docs and added link to create a SPN that I thought I had previously pushed!
> Typo and docs about SPN

- data-reconciliation-app/docs/data-schema-data-flow.md
Fix #194 
Review -
Data-Schema-Data-Flow.md
> data-schema-data-flow review

- data-reconciliation-app/docs/adr/09-api-documentation.md
> Update the API-Documentation ADR to reflect the latest swagger changes

- data-reconciliation-app/docs/adr/10-swagger-endpoint.md
> [ADR] - Improving Swagger Endpoint Security

- Makefile
- data-reconciliation-app/Makefile
- scripts/test_mccf.sh
This completes the demo flow as it never existed for mCCF.
> Allow make demo to work on mccf

- data-reconciliation-app/test/utils/jwt-config-generator.ts
Fix #211 
I have added a default timeout of 1 min.
Have tested it several times and it's not giving error.
> Fix - Timeout error in build

- data-reconciliation-app/Makefile
- data-reconciliation-app/src/auth/validator/jwt/ms-aad-jwt-provider.ts
- data-reconciliation-app/src/endpoints/app.json
- data-reconciliation-app/src/endpoints/swagger.ts
- data-reconciliation-app/src/utils/api-result.ts
- data-reconciliation-app/src/utils/config.ts
- deploy/New-IdentityProvider.ps1
- scripts/devContainer_OnStart.sh
- Enable user authentication in Swagger UI using Microsoft Identity
- Update AuthenticationService.ts to read the APIAppId and ClientId from config rather than hardcoded
> Enable user authentication in Swagger UI using Microsoft Identity

- data-reconciliation-app/docs/data-reconciliation.md
Fix #222 
Docs review - Data Reconciliation
> review data reconciliation

- data-reconciliation-app/docs/README.md
Small PR - add readme to docs folder + explain what ADRs are
> Create README for docs folder

- data-reconciliation-app/test/unit-test/auth/validator/jwt/demo-jwt-provider.test.ts
- data-reconciliation-app/test/unit-test/auth/validator/jwt/jwt-validation.test.ts
- data-reconciliation-app/test/unit-test/auth/validator/jwt/ms-aad-jwt-provider.test.ts
Fix #191 
Added unit-test for auth folder.
> auth unit test
